<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd5410ca1954452b0c75714ad0c90a981
{
    public static $prefixLengthsPsr4 = array (
        'T' =>
        array (
            'Tests\\' => 6,
        ),
        'D' =>
        array (
            'Dompdf\\' => 7,
            'Database\\Seeders\\' => 17,
            'Database\\Factories\\' => 19,
        ),
        'A' =>
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Tests\\' =>
        array (
            0 => __DIR__ . '/../..' . '/tests',
        ),
        'Dompdf\\' =>
        array (
            0 => __DIR__ . '/..' . '/dompdf/dompdf/src',
        ),
        'Database\\Seeders\\' =>
        array (
            0 => __DIR__ . '/../..' . '/database/seeders',
        ),
        'Database\\Factories\\' =>
        array (
            0 => __DIR__ . '/../..' . '/database/factories',
        ),
        'App\\' =>
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd5410ca1954452b0c75714ad0c90a981::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd5410ca1954452b0c75714ad0c90a981::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitd5410ca1954452b0c75714ad0c90a981::$classMap;

        }, null, ClassLoader::class);
    }
}
